// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0qODkfgQ8YtnHWsvmVg1MoXKsRkR2hJs',
    appId: '1:208974621702:web:f0f3c02c1d68fec4ae6787',
    messagingSenderId: '208974621702',
    projectId: 'vehicle-vault-5d77f',
    authDomain: 'vehicle-vault-5d77f.firebaseapp.com',
    storageBucket: 'vehicle-vault-5d77f.appspot.com',
    measurementId: 'G-1S3J4NPSSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-aHkaE8k76htyPJCS1TZQn9vYpUFksT8',
    appId: '1:208974621702:android:aae1286c36e7f8f0ae6787',
    messagingSenderId: '208974621702',
    projectId: 'vehicle-vault-5d77f',
    storageBucket: 'vehicle-vault-5d77f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyY6gl9TpM4n4ywwO1v1zp0351AnAwxTM',
    appId: '1:208974621702:ios:2c12a901d704804cae6787',
    messagingSenderId: '208974621702',
    projectId: 'vehicle-vault-5d77f',
    storageBucket: 'vehicle-vault-5d77f.appspot.com',
    iosBundleId: 'com.example.maintenanceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyY6gl9TpM4n4ywwO1v1zp0351AnAwxTM',
    appId: '1:208974621702:ios:2c12a901d704804cae6787',
    messagingSenderId: '208974621702',
    projectId: 'vehicle-vault-5d77f',
    storageBucket: 'vehicle-vault-5d77f.appspot.com',
    iosBundleId: 'com.example.maintenanceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0qODkfgQ8YtnHWsvmVg1MoXKsRkR2hJs',
    appId: '1:208974621702:web:ac345a7834f00c19ae6787',
    messagingSenderId: '208974621702',
    projectId: 'vehicle-vault-5d77f',
    authDomain: 'vehicle-vault-5d77f.firebaseapp.com',
    storageBucket: 'vehicle-vault-5d77f.appspot.com',
    measurementId: 'G-C3R612NS19',
  );
}
